
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.olc1.analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PRODUCTO = 9;
  public static final int CADENA = 3;
  public static final int MENOS = 8;
  public static final int TRUE = 11;
  public static final int ENTERO = 2;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int FALSE = 12;
  public static final int REAL = 4;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int DIVISION = 10;
  public static final int SEMICOLON = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "CADENA",
  "REAL",
  "SEMICOLON",
  "COMMA",
  "MAS",
  "MENOS",
  "PRODUCTO",
  "DIVISION",
  "TRUE",
  "FALSE"
  };
}

